#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================


# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "catppuccin-latte"
    colorscheme = "catppuccin" # Dark theme
    colorscheme_bg = "light"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode = false
    # tabulations
    default_indent = 4
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # file tree to the left
    filetree_direction = "left"
    # Enable autoload/myspacevim.vim (a classic neovim configuration)
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    # Use COC as autocomplete engine
    autocomplete_method = "coc"

    # Status line options
    # Enable/Disable show mode on statusline
    enable_statusline_mode = true
    
    # Show full path on statusline
    enable_statusline_bfpath = true

    # Components of status line
    statusline_right_sections = [
       'date',
       'time'
    ]

# Enable checkers ? => this might not work
[[layers]]
    name = "checkers"
    # nothing works here: set it up in myspacevim instead.

# LSP layer
# The lsp layer has to be enabled too. SpaceVim converts the configuration in the lsp layer and then passes it to coc.
# You can put your language servers here.
[[layers]] 
    name = 'lsp'
    filetypes = [
        'python'
    ]

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'

# Terminal configuration layer
[[layers]]
    name = 'shell'
    default_position = 'right'
    default_weight = 40

# Python layer
[[layers]]
    name = "lang#python"
    python_interpreter = "/home/goncalo/Work/venvs/base/bin/python3"
    enabled_linters = ['python', 'pylint']

[[layers]]
  name = "git"
  git_plugin = 'fugitive'

# === CUSTOM PLUGINS ===

[[custom_plugins]]
    # Theme
    name = 'https://github.com/liuchengxu/space-vim-theme'
    merged = 0
[[custom_plugins]]
    name = 'https://github.com/catppuccin/nvim'
    merged = 0

[[custom_plugins]]
    # FZF
    name = 'https://github.com/junegunn/fzf'
    merged = 0
[[custom_plugins]]
    name = 'https://github.com/junegunn/fzf.vim'
    merged = 0

[[custom_plugins]]
    # VScode like minimap
    name = "https://github.com/wfxr/minimap.vim"
    merged = 0

[[custom_plugins]]
    # Distraction free mode (goyo)
    name = "https://github.com/junegunn/goyo.vim"
    merged = 0
